FROM golang:1.21-alpine
RUN apk update && apk upgrade && \
                    apk add --no-cache bash git && \
                    apk add --update npm
RUN apk add --no-cache autoconf automake libtool gettext gettext-dev make g++ texinfo curl
WORKDIR /root
RUN npm install -g nodemon
WORKDIR /opt/app